/**
 * CSS property file for Entrainer.
 *
 * Edit this to change the look of Entrainer.  Instructions for
 * editing JavaFX CSS files can be found at:
 *
 * http://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html
 * http://docs.oracle.com/javafx/2/css_tutorial/jfxpub-css_tutorial.htm
 *
 */

/*
 * The root element defines properties for all JavaFX components.
 */
.root {
}

.menu-bar {
	-fx-background-color: derive(midnightblue, -50.0%);	
}

.menu-bar .label {
	-fx-text-fill: cornsilk;
}

.menu-bar .menu:hover {
     -fx-background-color: royalblue;
}

.menu-bar .menu:showing {
     -fx-background-color: royalblue;
}

.menu .label {
	-fx-text-fill: cornsilk;
}

.menu:focused {
     -fx-background-color: royalblue;
}

.menu-item:focused {
     -fx-background-color: royalblue;
}

.context-menu {
    -fx-skin: "com.sun.javafx.scene.control.skin.ContextMenuSkin";
    -fx-background-color: midnightblue;
    -fx-background-insets: 0.0, 1.0, 2.0;
    -fx-background-radius: 0.0 6.0 6.0 6.0, 0.0 5.0 5.0 5.0, 0.0 4.0 4.0 4.0;
    -fx-padding: 0.333333em 0.083333em 0.666667em 0.083333em;
    -fx-opacity: 0.75;
}

.check-box {
	-fx-text-fill: cornsilk;
}

.check-box .box {
    -fx-background-color: royalblue;
}

.check-box:selected .box .mark {
    -fx-background-color: black;
}

.radio-button {
	-fx-text-fill: cornsilk;
}

.radio-button .radio {
    -fx-background-color: royalblue;
}

.radio-button .radio .dot {
    -fx-background-color: royalblue;
}

.radio-button:selected .radio .dot {
    -fx-background-color: black;
}

.label {
	-fx-text-fill: cornsilk;
}

.titled-pane {
	-fx-text-fill: cornsilk;
	-fx-background-color: black;
    -fx-background-radius: 0.0 6.0 6.0 6.0, 0.0 5.0 5.0 5.0, 0.0 4.0 4.0 4.0;
}

.titled-pane .title {
    -fx-background-color: derive(midnightblue, -50.0%);
}

.text-field {
	-fx-text-fill: cornsilk;
	-fx-background-color: midnightblue;	
}

.combo-box {
	-fx-background-color: midnightblue;		
}

.combo-box .list-cell {
	-fx-text-fill: cornsilk;
	-fx-background-color: midnightblue;
}

.combo-box .combo-box-popup .list-view {
	-fx-opacity: 0.75;
}

.color-picker {
	-fx-background-color: midnightblue;		
}

.spinner .increment-arrow-button {
	-fx-background-color: royalblue;		
}

.spinner .increment-arrow-button .increment-arrow {
	-fx-background-color: black;		
}

.spinner .decrement-arrow-button {
	-fx-background-color: royalblue;		
}

.spinner .decrement-arrow-button .decrement-arrow {
	-fx-background-color: black;		
}

.slider .track {
	-fx-background-color: midnightblue;		
}

.slider .thumb {
	-fx-background-color: derive(midnightblue, 100.0%);		
}

.dialog-pane {
	-fx-background-color: black;		
	-fx-text-fill: cornsilk;
}

.dialog-pane .header-panel {
	-fx-background-color: royalblue;
}

.button {
	-fx-background-color: midnightblue;		
	-fx-text-fill: cornsilk;
}

.button:armed {
	-fx-background-color: royalblue;		
	-fx-text-fill: cornsilk;
}

.toggle-button {
	-fx-background-color: midnightblue;		
	-fx-text-fill: cornsilk;
}

.toggle-button:armed {
	-fx-background-color: royalblue;		
	-fx-text-fill: cornsilk;
}

.toggle-button:selected {
	-fx-background-color: derive(midnightblue, 100.0%);		
	-fx-text-fill: cornsilk;
}

.text-area {
	-fx-text-fill: cornsilk;
}

.text-area .content {
	-fx-background-color: midnightblue;		
}

#EntrainerFX-layout {
}

#AnimationPane-layout {
    -fx-background-color: black;	
}

#BackgroundPicturePane-layout {
    -fx-background-color: black;	
}

#FlashOptionsPane-layout {
    -fx-background-color: black;	
}

#MediaPlayerPane-layout {
    -fx-background-color: black;	
}

#ShimmerOptionsPane-layout {
    -fx-background-color: black;	
}

#SliderControlPane-layout {
    -fx-background-color: black;	
}

#NeuralizerPane-layout {
    -fx-background-color: black;	
}

#NeuronGrid-layout {
    -fx-background-color: black;	
}